# Generated by Django 5.1.4 on 2026-07-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CB', 'Chef de Brigade'), ('AB', 'AB Entheos'), ('WCS', 'WCS'), ('DGFC', 'DGFC'), ('DGFAP', 'DGFAP'), ('MINISTER', 'Minister'), ('ADMIN', 'Administrator'), ('SUPER_ADMIN', 'Super Administrator')], max_length=16),
        ),
    ]
