# Generated by Django 5.1.4 on 2026-08-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_recipie_e84b87_idx',
            old_name='notifications_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_recipie_2cb2ac_idx',
            old_name='notifications_recipient_created_idx',
        ),
    ]
