# Generated by Django 5.1.4 on 2026-07-16 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_ceiling_xaf', models.PositiveIntegerField(default=2000000)),
                ('burial_ceiling_xaf', models.PositiveIntegerField(default=1500000)),
                ('first_aid_pct', models.PositiveSmallIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund settings',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_type', models.CharField(choices=[('MEDICAL', 'Medical (injury)'), ('BURIAL', 'Burial (death)')], default='MEDICAL', max_length=16)),
                ('claimant_name', models.CharField(max_length=200)),
                ('claimant_phone', models.CharField(blank=True, max_length=32)),
                ('incident_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('AT_APPROVAL', 'At approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('amount_authorized', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('priority_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('urgent_medical', models.BooleanField(default=False)),
                ('first_aid_released', models.BooleanField(default=False)),
                ('first_aid_amount_xaf', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='accounts.village')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ADVANCED', 'Advanced'), ('REJECTED', 'Rejected'), ('AMOUNT_SET', 'Amount set'), ('FIRST_AID_RELEASED', 'First-aid released'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('COMMENT', 'Comment')], max_length=32)),
                ('from_step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['current_step'], name='cases_case_current_c2237e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['village'], name='cases_case_village_b9bcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['case', 'occurred_at'], name='cases_event_case_id_2a327b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['actor'], name='cases_event_actor_i_b06978_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='cases_event_event_t_9e28da_idx'),
        ),
    ]
