# Generated by Django 5.1.4 on 2026-07-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_event_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsettings',
            name='crop_ceiling_xaf',
            field=models.PositiveIntegerField(default=400000),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical (injury)'), ('BURIAL', 'Burial (death)'), ('CROP_DAMAGE', 'Crop damage')], default='MEDICAL', max_length=16),
        ),
    ]
