# Generated by Django 5.1.4 on 2026-07-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_fundsettings_crop_ceiling_xaf_alter_case_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('AT_APPROVAL', 'At approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEFERRED', 'Deferred'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ADVANCED', 'Advanced'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('AMOUNT_SET', 'Amount set'), ('FIRST_AID_RELEASED', 'First-aid released'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('COMMENT', 'Comment')], max_length=32),
        ),
    ]
