# Generated by Django 5.1.4 on 2026-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_disbursements_drop_accelerated'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disbursement',
            new_name='cases_disbu_case_id_e165b4_idx',
            old_name='cases_disbu_case_id_7a9b35_idx',
        ),
        migrations.RemoveField(
            model_name='case',
            name='priority_score',
        ),
        migrations.AddField(
            model_name='case',
            name='amount_proposed',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Proposed amount by DGFC at step 4, visible to DGFAP at step 5.', max_digits=14, null=True),
        ),
    ]
