# Generated by Django 5.1.4 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_amount_proposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount_xaf',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Amount set by the actor (proposed or authorized), copied from the set_amount view.', max_digits=14, null=True),
        ),
    ]