# Generated by Django 5.1.4 on 2026-07-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_event_amount_xaf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ADVANCED', 'Advanced'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('AMOUNT_PROPOSED', 'Amount proposed'), ('AMOUNT_AUTHORIZED', 'Amount authorized'), ('APPROVED', 'Approved'), ('DISBURSEMENT_RECORDED', 'Disbursement recorded'), ('DISBURSEMENT_UPDATED', 'Disbursement updated'), ('DISBURSEMENT_DELETED', 'Disbursement deleted'), ('PROOF_UPLOADED', 'Proof of payment uploaded'), ('CLOSED', 'Closed'), ('COMMENT', 'Comment')], max_length=32),
        ),
    ]
