# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_disbursement_soft_delete_and_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='claimant_id_number',
            field=models.CharField(blank=True, help_text='National ID or passport number', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='claimant_id_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NATIONAL_ID', 'National ID'),
                    ('PASSPORT', 'Passport'),
                    ('DRIVER_LICENSE', 'Driver License'),
                    ('OTHER', 'Other'),
                ],
                default='NATIONAL_ID',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='case',
            name='claimant_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='claimant_gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('M', 'Male'),
                    ('F', 'Female'),
                    ('OTHER', 'Other'),
                ],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name='case',
            name='claimant_address',
            field=models.CharField(blank=True, help_text='Full address of the claimant', max_length=300),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_location',
            field=models.CharField(blank=True, help_text='Location where the incident occurred', max_length=300),
        ),
        migrations.AddField(
            model_name='case',
            name='relationship_to_claimant',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SELF', 'Self'),
                    ('SPOUSE', 'Spouse'),
                    ('PARENT', 'Parent'),
                    ('CHILD', 'Child'),
                    ('SIBLING', 'Sibling'),
                    ('OTHER', 'Other'),
                ],
                default='SELF',
                max_length=32,
            ),
        ),
    ]
