# Generated by Django 5.1.4 on 2026-07-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_kyc_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ADVANCED', 'Advanced'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('AMOUNT_PROPOSED', 'Amount proposed'), ('AMOUNT_AUTHORIZED', 'Amount authorized'), ('APPROVED', 'Approved'), ('DISBURSEMENT_RECORDED', 'Disbursement recorded'), ('DISBURSEMENT_UPDATED', 'Disbursement updated'), ('DISBURSEMENT_DELETED', 'Disbursement deleted'), ('PROOF_UPLOADED', 'Proof of payment uploaded'), ('FILE_DELETED', 'File deleted'), ('CLOSED', 'Closed'), ('COMMENT', 'Comment')], max_length=32),
        ),
    ]
