# Generated by hand to add FILE_SUPERSEDED to the Event.event_type enum.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ADVANCED', 'Advanced'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('AMOUNT_PROPOSED', 'Amount proposed'), ('AMOUNT_AUTHORIZED', 'Amount authorized'), ('APPROVED', 'Approved'), ('DISBURSEMENT_RECORDED', 'Disbursement recorded'), ('DISBURSEMENT_UPDATED', 'Disbursement updated'), ('DISBURSEMENT_DELETED', 'Disbursement deleted'), ('PROOF_UPLOADED', 'Proof of payment uploaded'), ('FILE_DELETED', 'File deleted'), ('FILE_SOFT_DELETED', 'File soft-deleted (retained for audit)'), ('FILE_SUPERSEDED', 'File replaced (old version retained for history)'), ('CLOSED', 'Closed'), ('COMMENT', 'Comment')], max_length=32),
        ),
    ]
