# Generated by Django 5.1.4 on 2026-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_case_village_name_and_chef_de_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='recipient_kind_other',
            field=models.CharField(blank=True, default='', help_text='Free-text when recipient_kind is OTHER', max_length=200),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='payment_reference',
            field=models.CharField(max_length=128),
        ),
    ]
