# Generated by Django 5.1.4 on 2026-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_fundsettings_burial_ceiling_3m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsettings',
            name='burial_ceiling_xaf',
            field=models.PositiveIntegerField(default=3000000),
        ),
    ]
