# Generated by Django 5.1.4 on 2026-07-16 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('schema', models.JSONField(help_text='Bilingual JSONB. See master doc §6 — field labels as {en, fr}.')),
                ('role_scope', models.CharField(help_text='Comma-separated role codes allowed to fill this form.', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', 'slug'],
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('role_at_submission', models.CharField(max_length=16)),
                ('payload', models.JSONField()),
                ('version', models.PositiveSmallIntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cases.case')),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.formdefinition')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=256)),
                ('mime', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected')], default='PENDING', max_length=16)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forms.formsubmission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['case'], name='forms_forms_case_id_df4fee_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form_definition'], name='forms_forms_form_de_e34078_idx'),
        ),
    ]
