# Generated by Django 5.1.4 on 2026-07-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_legacy_label_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
    ]
