# Generated by Django 5.1.4 on 2026-07-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_add_file_type_to_formattachment'),
        ('forms', '0005_attachment_description'),
    ]

    operations = [
    ]
