# Generated by Django 5.1.4 on 2026-07-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_attachment_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='formattachment',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='If this attachment was replaced, points to the newer one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='forms.formattachment'),
        ),
    ]
